name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install-ubuntu
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: install-windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon check (library)
        run: |
          moon check -C lib --target all

      - name: moon test (library)
        run: |
          moon test -C lib --target all

      - name: moon lint (library)
        run: |
          moon fmt -C lib && git diff --exit-code
          moon info -C lib && git diff --exit-code
  
      - name: moon check (plugin)
        run: |
          moon check -C plugin --target all

      - name: moon test (plugin)
        run: |
          moon test -C plugin --target all

      - name: moon lint (plugin)
        run: |
          moon fmt -C plugin && git diff --exit-code
          moon info -C plugin && git diff --exit-code

      - name: moon check (cli)
        run: |
          moon check -C cli --target all  

      - name: moon test (cli)
        run: |
          moon test -C cli --target all 

      - name: moon lint (cli)
        run: |
          moon fmt -C cli && git diff --exit-code 
          moon info -C cli && git diff --exit-code