name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install-ubuntu
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Install protoscope
        run: |
          go install github.com/protocolbuffers/protoscope/cmd/protoscope...@latest

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            version: 31.1

      - name: version & update
        run: |
          moon version --all
          moon update
          protoc --version

      - name: moon library test
        run: |
          moon install -C lib
          moon test -C lib --target native

      - name: moon plugin test
        run: |
          moon install -C plugin
          moon test -C plugin --target native

      - name: moon cli test
        run: |
          moon install -C cli
          moon test -C cli --target native
      
      - name: reader test
        shell: bash
        run: |
          PROTOC_ROOT=$(dirname $(dirname $(which protoc)))
          PROTOC_INCLUDE_PATH="$PROTOC_ROOT/include"
          python3 scripts/reader_test.py --include-path "$PROTOC_INCLUDE_PATH"

      - name: snapshot test
        shell: bash
        run: |
          PROTOC_ROOT=$(dirname $(dirname $(which protoc)))
          PROTOC_INCLUDE_PATH="$PROTOC_ROOT/include"
          python3 scripts/snapshot_test.py --include-path "$PROTOC_INCLUDE_PATH"
